spring:
  datasource:
    url: jdbc:postgresql://postgres-dev:5432/productapi
    username: dev
    password: devpass123
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    
# Microservices configuration for development
microservices:
  inventory:
    base-url: "http://localhost:8082"  # Local inventory service
    health-endpoint: "/actuator/health"
    
# Eureka configuration for development (optional)
eureka:
  client:
    enabled: false  # Disable by default in dev, can be overridden
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    com.cristianino.productapi: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    root: INFO