# Configuración para ambiente de producción
server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/productdb}
    username: ${DATABASE_USERNAME:productuser}
    password: ${DATABASE_PASSWORD:productpass}
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      
logging:
  level:
    com.cristianino.productapi: INFO
    org.springframework.security: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Microservices configuration for production
microservices:
  inventory:
    base-url: ${INVENTORY_SERVICE_URL:http://inventory-service:8081}

# Eureka configuration for production
eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${HOSTNAME:localhost}