spring:
  datasource:
    url: jdbc:postgresql://postgres-dev:5432/productapi
    username: dev
    password: devpass123
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    
logging:
  level:
    com.cristianino.productapi: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    root: INFO